export const STOCKS_INFO = [
  {
    symbol: "786",
    name: "786 Investments Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AABS",
    name: "Al-Abbas Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AATM",
    name: "Ali Asghar Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ABL",
    name: "Allied Bank Limited",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ABOT",
    name: "Abbott Laboratories (Pakistan) Limited",
    sectorName: "PHARMACEUTICALS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ACIETF",
    name: "Alfalah Consumer Index (ETF)",
    sectorName: "EXCHANGE TRADED FUNDS",
    isETF: true,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ACPL",
    name: "Attock Cement Pakistan Limited",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ADAMS",
    name: "Adam Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ADMM",
    name: "Artistic Denim Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AGHA",
    name: "Agha Steel Ind.Ltd",
    sectorName: "ENGINEERING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AGIC",
    name: "Askari General Insurance Company Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AGIL",
    name: "Agriauto Industries Limited",
    sectorName: "AUTOMOBILE PARTS & ACCESSORIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AGL",
    name: "Agritech Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AGLNCPS",
    name: "Agritech Non-Voting (Pref) Class A",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AGP",
    name: "AGP Limited",
    sectorName: "PHARMACEUTICALS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AGSML",
    name: "Abdullah Shah Ghazi Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AGTL",
    name: "Al-Ghazi Tractors Limited",
    sectorName: "AUTOMOBILE ASSEMBLER",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AHCL",
    name: "Arif Habib Corporation Limited",
    sectorName: "FERTILIZER",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AHL",
    name: "Arif Habib Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AHTM",
    name: "Ahmad Hassan Textile Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AICL",
    name: "Adamjee Insurance Company Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AIRLINK",
    name: "Air Link Communication Limited",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AKBL",
    name: "Askari Bank Limited",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AKDHL",
    name: "AKD Hospitality Limited",
    sectorName: "MISCELLANEOUS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AKDSL",
    name: "AKD Securities Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AKGL",
    name: "Al-Khair Gadoon Limited",
    sectorName: "MISCELLANEOUS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ALAC",
    name: "Askari Life Assurance Company Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ALIFE",
    name: "Adamjee Life Assurance Company Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ALNRS",
    name: "Al-Noor Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ALTN",
    name: "Altern Energy Limited",
    sectorName: "POWER GENERATION & DISTRIBUTION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AMBL",
    name: "Apna Microfinance Bank Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ANL",
    name: "Azgard Nine Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ANLPS",
    name: "Azgard Nine 8.95%(Pref)",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ANTM",
    name: "AN Textile Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "APL",
    name: "Attock Petroleum Limited",
    sectorName: "OIL & GAS MARKETING COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ARCTM",
    name: "Arctic Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ARPAK",
    name: "Arpak International Investments Ltd.",
    sectorName: "MISCELLANEOUS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ARPL",
    name: "Archroma Pakistan Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ASC",
    name: "Al Shaheer Corporation Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ASHT",
    name: "Ashfaq Textile Mills Limited",
    sectorName: "TEXTILE WEAVING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ASIC",
    name: "Asia Insurance Company Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ASL",
    name: "Aisha Steel Mills Limited",
    sectorName: "ENGINEERING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ASLCPS",
    name: "Aisha Steel Convt (Pref) Right",
    sectorName: "ENGINEERING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ASLPS",
    name: "Aisha Steel Convertible (Pref)",
    sectorName: "ENGINEERING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ASTL",
    name: "Amreli Steels Limited",
    sectorName: "ENGINEERING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ASTM",
    name: "Asim Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ATBA",
    name: "Atlas Battery Limited",
    sectorName: "AUTOMOBILE PARTS & ACCESSORIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ATIL",
    name: "Atlas Insurance Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ATLH",
    name: "Atlas Honda Limited",
    sectorName: "AUTOMOBILE ASSEMBLER",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ATRL",
    name: "Attock Refinery Limited",
    sectorName: "REFINERY",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AVN",
    name: "Avanceon Limited",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "AWTX",
    name: "Allawasaya Tex. & Finishing Mills Ltd",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BAFL",
    name: "Bank Alfalah Limited",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BAFS",
    name: "Baba Farid Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BAHL",
    name: "Bank AL Habib Limited",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BAPL",
    name: "Bawany Air Products Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BATA",
    name: "Bata Pakistan Limited",
    sectorName: "LEATHER & TANNERIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BBFL",
    name: "Big Bird Foods Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BCL",
    name: "Bolan Castings Limited",
    sectorName: "ENGINEERING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BECO",
    name: "Beco Steel Limited",
    sectorName: "ENGINEERING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BERG",
    name: "Berger Paints Pakistan Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BFAGRO",
    name: "Barkat Frisian Agro Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BFBIO",
    name: "BF Biosciences Limited",
    sectorName: "PHARMACEUTICALS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BFMOD",
    name: "B.F. Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BGL",
    name: "Baluchistan Glass Limited",
    sectorName: "GLASS & CERAMICS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BHAT",
    name: "Bhanero Textile Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BIFO",
    name: "Biafo Industries Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BIPL",
    name: "BankIslami Pakistan Limited",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BIPLS",
    name: "BIPL Securities Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BLUEX",
    name: "Blue-Ex Limited",
    sectorName: "TRANSPORT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BML",
    name: "Bank Makramah Limited",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BNL",
    name: "Bunnys Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BNWM",
    name: "Bannu Woollen Mills Limited",
    sectorName: "WOOLLEN",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BOK",
    name: "The Bank of Khyber",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BOP",
    name: "The Bank of Punjab",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BPL",
    name: "Burshane LPG (Pakistan) Limited",
    sectorName: "OIL & GAS MARKETING COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BROT",
    name: "Brothers Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BRRG",
    name: "B.R.R Guardian Limited",
    sectorName: "PROPERTY",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BTL",
    name: "Blessed Textiles Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BUXL",
    name: "Buxly Paints Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BWCL",
    name: "Bestway Cement Limited",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "BWHL",
    name: "Baluchistan Wheels Limited",
    sectorName: "AUTOMOBILE PARTS & ACCESSORIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CASH",
    name: "Calcorp Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CCM",
    name: "Crescent Cotton Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CENI",
    name: "Century Insurance Company Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CEPB",
    name: "Century Paper & Board Mills Limited",
    sectorName: "PAPER, BOARD & PACKAGING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CFL",
    name: "Crescent Fibres Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CHAS",
    name: "Chashma Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CHBL",
    name: "Chenab Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CHCC",
    name: "Cherat Cement Company Limited",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CLCPS",
    name: "Chenab Limited (Pref)",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CLOV",
    name: "Clover Pakistan Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CLVL",
    name: "Cordoba Logistics & Ventures Limited",
    sectorName: "TRANSPORT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CNERGY",
    name: "Cnergyico PK  Limited",
    sectorName: "REFINERY",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "COLG",
    name: "Colgate-Palmolive (Pakistan) Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CPHL",
    name: "Citi Pharma Ltd.",
    sectorName: "PHARMACEUTICALS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CPPL",
    name: "Cherat Packaging Limited",
    sectorName: "PAPER, BOARD & PACKAGING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CRTM",
    name: "The Crescent Textile Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CSAP",
    name: "Crescent Steel & Allied Products Limited",
    sectorName: "ENGINEERING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CSIL",
    name: "Crescent Star Insurance Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CTM",
    name: "Colony Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "CYAN",
    name: "Cyan Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DAAG",
    name: "Data Agro Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DADX",
    name: "Dadex Eternit Limited",
    sectorName: "ENGINEERING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DAWH",
    name: "Dawood Hercules Corporation Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DBCI",
    name: "Dadabhoy Cement Industries Limited",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DCL",
    name: "Dewan Cement Limited",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DCR",
    name: "Dolmen City REIT",
    sectorName: "REAL ESTATE INVESTMENT TRUST",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DEL",
    name: "Dawood Equities Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DFML",
    name: "Dewan Farooque Motors Limited",
    sectorName: "AUTOMOBILE ASSEMBLER",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DFSM",
    name: "Dewan Farooque Spinning Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DGKC",
    name: "D.G. Khan Cement Company Limited",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DHPL",
    name: "DH Partners Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DIIL",
    name: "Diamond Industries Limited",
    sectorName: "MISCELLANEOUS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DINT",
    name: "Din Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DLL",
    name: "Dawood Lawrencepur Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DMC",
    name: "D.M. Corporation Limited.",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DNCC",
    name: "Dandot Cement Company Limited",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DOL",
    name: "Descon Oxychem Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DSIL",
    name: "D.S. Industries Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "DYNO",
    name: "Dynea Pakistan Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ECOP",
    name: "Ecopack Limited",
    sectorName: "MISCELLANEOUS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "EFERT",
    name: "Engro Fertilizers Limited",
    sectorName: "FERTILIZER",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "EFUG",
    name: "EFU General Insurance Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "EFUL",
    name: "EFU Life Assurance Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ELCM",
    name: "Elahi Cotton Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ELSM",
    name: "Ellcot Spinning Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "EMCO",
    name: "Emco Industries Limited",
    sectorName: "CABLE & ELECTRICAL GOODS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ENGROH",
    name: "Engro Holdings Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "EPCL",
    name: "Engro Polymer & Chemicals Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "EPCLPS",
    name: "Engro Poly(Pref)",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "EPQL",
    name: "Engro Powergen Qadirpur Limited",
    sectorName: "POWER GENERATION & DISTRIBUTION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ESBL",
    name: "Escorts Investment Bank Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "EWIC",
    name: "East West Insurance Company Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "EXIDE",
    name: "Exide Pakistan Limited",
    sectorName: "AUTOMOBILE PARTS & ACCESSORIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FABL",
    name: "Faysal Bank Limited",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FANM",
    name: "First Al-Noor Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FASM",
    name: "Faisal Spinning Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FATIMA",
    name: "Fatima Fertilizer Company Limited",
    sectorName: "FERTILIZER",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FCCL",
    name: "Fauji Cement Company Limited",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FCEPL",
    name: "Frieslandcampina Engro Pakistan Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FCIBL",
    name: "First Credit and Investment Bank Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FCL",
    name: "Fast Cables Limited",
    sectorName: "CABLE & ELECTRICAL GOODS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FCONM",
    name: "First Constellation Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FCSC",
    name: "First Capital Securities Corporation",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FDPL",
    name: "First Dawood Properties Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FECM",
    name: "First Elite Capital Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FECTC",
    name: "Fecto Cement Limited",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FEM",
    name: "First Equity Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FEROZ",
    name: "Ferozsons Laboratories Limited",
    sectorName: "PHARMACEUTICALS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FFBL",
    name: "Fauji Fertilizer Bin Qasim Limited",
    sectorName: "FERTILIZER",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FFC",
    name: "Fauji Fertilizer Company Limited",
    sectorName: "FERTILIZER",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FFL",
    name: "Fauji Foods Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FFLM",
    name: "First Fidelity Leasing Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FHAM",
    name: "First Habib Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FIBLM",
    name: "First IBL Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FIMM",
    name: "First Imrooz Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FLYNG",
    name: "Flying Cement Company Limited",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FML",
    name: "Feroze1888 Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FNEL",
    name: "First National Equities Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FPJM",
    name: "First Punjab Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FPRM",
    name: "First Paramount Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FRCL",
    name: "Frontier Ceramics Limited",
    sectorName: "GLASS & CERAMICS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FRSM",
    name: "Faran Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FTMM",
    name: "First Treet Manufacturing Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FTSM",
    name: "First Tri-Star Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "FZCM",
    name: "Fazal Cloth Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GADT",
    name: "Gadoon Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GAL",
    name: "Ghandhara Automobiles Limited",
    sectorName: "AUTOMOBILE ASSEMBLER",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GAMON",
    name: "Gammon Pakistan Limited",
    sectorName: "MISCELLANEOUS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GATI",
    name: "Gatron (Industries) Limited",
    sectorName: "SYNTHETIC & RAYON",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GATM",
    name: "Gul Ahmed Textile Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GCIL",
    name: "Ghani Chemical Industries Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GCWL",
    name: "Ghani Chemworld Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GDL",
    name: "Ghani Dairies Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GEMBCEM",
    name: "Burj Clean Energy Modaraba(GEM)",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: true,
  },
  {
    symbol: "GEMBLUEX",
    name: "Blue-Ex Limited (GEM)",
    sectorName: "TRANSPORT",
    isETF: false,
    isDebt: false,
    isGEM: true,
  },
  {
    symbol: "GEMMEL",
    name: "Mughal Energy Limited(GEM)",
    sectorName: "POWER GENERATION & DISTRIBUTION",
    isETF: false,
    isDebt: false,
    isGEM: true,
  },
  {
    symbol: "GEMNETS",
    name: "Nets International Communication Limited",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: true,
  },
  {
    symbol: "GEMPACRA",
    name: "The Pakistan Credit Rating Agency Ltd",
    sectorName: "MISCELLANEOUS",
    isETF: false,
    isDebt: false,
    isGEM: true,
  },
  {
    symbol: "GEMPAPL",
    name: "Pak Agro Packaging Limited(GEM)",
    sectorName: "PAPER, BOARD & PACKAGING",
    isETF: false,
    isDebt: false,
    isGEM: true,
  },
  {
    symbol: "GFIL",
    name: "Ghazi Fabrics International Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GGGL",
    name: "Ghani Global Glass Limited",
    sectorName: "GLASS & CERAMICS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GGL",
    name: "Ghani Global Holdings Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GHGL",
    name: "Ghani Glass Limited",
    sectorName: "GLASS & CERAMICS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GHNI",
    name: "Ghandhara Industries Limited",
    sectorName: "AUTOMOBILE ASSEMBLER",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GIL",
    name: "Good Luck Industries Ltd.",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GLAXO",
    name: "GlaxoSmithKline Pakistan Limited",
    sectorName: "PHARMACEUTICALS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GLPL",
    name: "Gillette Pakistan Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GOC",
    name: "GOC (Pak) Limited.",
    sectorName: "MISCELLANEOUS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GRR",
    name: "Globe Residency REIT",
    sectorName: "REAL ESTATE INVESTMENT TRUST",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GRYL",
    name: "Grays Leasing Limited",
    sectorName: "LEASING COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GTYR",
    name: "Ghandhara Tyre & Rubber Company Limited",
    sectorName: "AUTOMOBILE PARTS & ACCESSORIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GVGL",
    name: "Ghani Value Glass Limited",
    sectorName: "GLASS & CERAMICS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "GWLC",
    name: "Gharibwal Cement Limited",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HABSM",
    name: "Habib Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HAEL",
    name: "Hala Enterprises Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HAFL",
    name: "Hafiz Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HALEON",
    name: "Haleon Pakistan Limited",
    sectorName: "PHARMACEUTICALS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HASCOL",
    name: "Hascol Petroleum Limited",
    sectorName: "OIL & GAS MARKETING COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HBL",
    name: "Habib Bank Limited",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HBLTETF",
    name: "HBL Total Treasury (ETF)",
    sectorName: "EXCHANGE TRADED FUNDS",
    isETF: true,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HCAR",
    name: "Honda Atlas Cars (Pakistan) Limited",
    sectorName: "AUTOMOBILE ASSEMBLER",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HCL",
    name: "Hallmark Company Limited",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HGFA",
    name: "HBL Growth Fund",
    sectorName: "CLOSE - END MUTUAL FUND",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HICL",
    name: "Habib Insurance Company Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HIFA",
    name: "HBL Investment Fund",
    sectorName: "CLOSE - END MUTUAL FUND",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HINO",
    name: "Hinopak Motors Limited",
    sectorName: "AUTOMOBILE ASSEMBLER",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HINOON",
    name: "Highnoon Laboratories Limited",
    sectorName: "PHARMACEUTICALS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HMB",
    name: "Habib Metropolitan Bank Limited",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HPL",
    name: "Hoechst Pakistan Limited",
    sectorName: "PHARMACEUTICALS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HRPL",
    name: "Habib Rice Product Limited.",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HTL",
    name: "Hi-Tech Lubricants Limited",
    sectorName: "OIL & GAS MARKETING COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HUBC",
    name: "The Hub Power Company Limited",
    sectorName: "POWER GENERATION & DISTRIBUTION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HUMNL",
    name: "Hum Network Limited",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "HUSI",
    name: "Husein Industries Limited",
    sectorName: "PROPERTY",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "IBFL",
    name: "Ibrahim Fibres Limited",
    sectorName: "SYNTHETIC & RAYON",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "IBLHL",
    name: "IBL HealthCare Limited",
    sectorName: "PHARMACEUTICALS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ICCI",
    name: "ICC Industries Limited",
    sectorName: "TEXTILE WEAVING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ICIBL",
    name: "Invest Capital Investment Bank Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ICL",
    name: "Ittehad Chemicals Limted",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "IDRT",
    name: "Idrees Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "IDSM",
    name: "Ideal Spinning Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "IDYM",
    name: "Indus Dyeing & Manufacturing Co. Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "IGIHL",
    name: "IGI Holdings Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "IGIL",
    name: "IGI Life Insurance Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ILP",
    name: "Interloop Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ILTM",
    name: "Island Textile Mills Limited",
    sectorName: "",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "IMAGE",
    name: "Image Pakistan Limited",
    sectorName: "SYNTHETIC & RAYON",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "IML",
    name: "Imperial  Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "IMS",
    name: "Intermarket Securities Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "INDU",
    name: "Indus Motor Company Limited",
    sectorName: "AUTOMOBILE ASSEMBLER",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "INIL",
    name: "International Industries Limited",
    sectorName: "ENGINEERING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "INKL",
    name: "International Knitwear Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "IPAK",
    name: "International Packaging Films Limited",
    sectorName: "PAPER, BOARD & PACKAGING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "IREIT",
    name: "Image Reit",
    sectorName: "REAL ESTATE INVESTMENT TRUST",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ISIL",
    name: "Ismail Industries Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ISL",
    name: "International Steels Limited",
    sectorName: "ENGINEERING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ITTEFAQ",
    name: "Ittefaq Iron Industries Limited",
    sectorName: "ENGINEERING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "JATM",
    name: "J.A. Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "JDMT",
    name: "Janana De Malucho Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "JDWS",
    name: "JDW Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "JGICL",
    name: "Jubilee General Insurance Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "JKSM",
    name: "J.K. Spinning Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "JLICL",
    name: "Jubilee Life Insurance Company Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "JSBL",
    name: "JS Bank Limited",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "JSCL",
    name: "Jahangir Siddiqui & Co. Ltd.",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "JSCLPSA",
    name: "Jahangir Sidd(Pref)",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "JSGBETF",
    name: "JS Global Banking Sector(ETF)",
    sectorName: "EXCHANGE TRADED FUNDS",
    isETF: true,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "JSGCL",
    name: "JS Global Capital Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "JSIL",
    name: "JS Investments Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "JSMFETF",
    name: "JS Momentum Factor Exchange Traded Fund",
    sectorName: "EXCHANGE TRADED FUNDS",
    isETF: true,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "JSML",
    name: "Jauharabad Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "JVDC",
    name: "Javedan Corporation Limited",
    sectorName: "PROPERTY",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "JVDCPS",
    name: "Javedan Corporation (Pref)",
    sectorName: "PROPERTY",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "KAPCO",
    name: "Kot Addu Power Company Limited",
    sectorName: "POWER GENERATION & DISTRIBUTION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "KCL",
    name: "Karam Ceramics Limited",
    sectorName: "GLASS & CERAMICS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "KEL",
    name: "K-Electric Limited",
    sectorName: "POWER GENERATION & DISTRIBUTION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "KHTC",
    name: "Khyber Tobacco Company Limited",
    sectorName: "TOBACCO",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "KHYT",
    name: "Khyber Textile Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "KML",
    name: "Kohinoor Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "KOHC",
    name: "Kohat Cement Company Limited",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "KOHE",
    name: "Kohinoor Energy Limited",
    sectorName: "POWER GENERATION & DISTRIBUTION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "KOHP",
    name: "Kohinoor Power Company Limited",
    sectorName: "POWER GENERATION & DISTRIBUTION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "KOHTM",
    name: "Kohat Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "KOIL",
    name: "Kohinoor Industries Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "KOSM",
    name: "Kohinoor Spinning Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "KPUS",
    name: "Khairpur Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "KSBP",
    name: "KSB Pumps Company Limited",
    sectorName: "ENGINEERING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "KTML",
    name: "Kohinoor Textile Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "LCI",
    name: "Lucky Core Industries Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "LEUL",
    name: "Leather Up Limited",
    sectorName: "LEATHER & TANNERIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "LIVEN",
    name: "Liven Pharma Limited",
    sectorName: "PHARMACEUTICALS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "LOADS",
    name: "Loads Limited",
    sectorName: "AUTOMOBILE PARTS & ACCESSORIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "LOTCHEM",
    name: "Lotte Chemical Pakistan Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "LPGL",
    name: "Leiner Pak Gelatine Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "LPL",
    name: "Lalpir Power Limited",
    sectorName: "POWER GENERATION & DISTRIBUTION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "LSECL",
    name: "LSE Capital Limited.",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "LSEFSL",
    name: "LSE Financial Services Limited.",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "LSEVL",
    name: "LSE Ventures Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "LUCK",
    name: "Lucky Cement Limited",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MACFL",
    name: "MACPAC Films Limited",
    sectorName: "PAPER, BOARD & PACKAGING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MACTER",
    name: "Macter International Limited",
    sectorName: "PHARMACEUTICALS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MARI",
    name: "Mari Petroleum Company Limited",
    sectorName: "OIL & GAS EXPLORATION COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MCB",
    name: "MCB Bank Limited",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MCBIM",
    name: "MCB Investment Management Limited.",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MDTL",
    name: "Media Times Limited",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MEBL",
    name: "Meezan Bank Limited",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MEHT",
    name: "Mehmood Textile Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MERIT",
    name: "Merit Packaging Limited",
    sectorName: "PAPER, BOARD & PACKAGING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MFFL",
    name: "Mitchells Fruit Farms Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MFL",
    name: "Matco Foods Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MIIETF",
    name: "Mahaana Islamic Index ETF",
    sectorName: "EXCHANGE TRADED FUNDS",
    isETF: true,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MIRKS",
    name: "Mirpurkhas Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MLCF",
    name: "Maple Leaf Cement Factory Limited",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MQTM",
    name: "Maqbool Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MRNS",
    name: "Mehran Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MSCL",
    name: "Metropolitan Steel Corporation Limited",
    sectorName: "ENGINEERING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MSOT",
    name: "Masood Textile Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MSOTPS",
    name: "Masood Textile (Pref)",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MTL",
    name: "Millat Tractors Limited",
    sectorName: "AUTOMOBILE ASSEMBLER",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MUGHAL",
    name: "Mughal Iron & Steel Industries Limited",
    sectorName: "ENGINEERING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MUGHALC",
    name: "Mughal Iron & Steel Industries Ltd(C)",
    sectorName: "ENGINEERING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MUREB",
    name: "Murree Brewery Company Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MWMP",
    name: "Mandviwala Mauser Plastic Industries",
    sectorName: "MISCELLANEOUS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "MZNPETF",
    name: "Meezan Pakistan ETF",
    sectorName: "EXCHANGE TRADED FUNDS",
    isETF: true,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "NAGC",
    name: "Nagina Cotton Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "NATF",
    name: "National Foods Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "NATM",
    name: "Nadeem Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "NBP",
    name: "National Bank of Pakistan",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "NBPGETF",
    name: "NBP Pakistan  Growth ETF",
    sectorName: "EXCHANGE TRADED FUNDS",
    isETF: true,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "NCL",
    name: "Nishat Chunian Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "NCPL",
    name: "Nishat Chunian Power Limited",
    sectorName: "POWER GENERATION & DISTRIBUTION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "NESTLE",
    name: "Nestle Pakistan Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "NETSOL",
    name: "NetSol Technologies Limited",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "NEXT",
    name: "Next Capital Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "NICL",
    name: "Nimir Industrial Chemicals Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "NITGETF",
    name: "NIT Pakistan Gateway ETF",
    sectorName: "EXCHANGE TRADED FUNDS",
    isETF: true,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "NML",
    name: "Nishat Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "NONS",
    name: "Noon Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "NPL",
    name: "Nishat Power Limited",
    sectorName: "POWER GENERATION & DISTRIBUTION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "NRL",
    name: "National Refinery Limited",
    sectorName: "REFINERY",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "NRSL",
    name: "Nimir Resins Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "NSRM",
    name: "The National Silk & Rayon Mills Limited",
    sectorName: "SYNTHETIC & RAYON",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "OBOY",
    name: "Oilboy Energy Limited",
    sectorName: "OIL & GAS MARKETING COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "OCTOPUS",
    name: "Octopus Digital Limited",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "OGDC",
    name: "Oil & Gas Development Company Limited",
    sectorName: "OIL & GAS EXPLORATION COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "OLPL",
    name: "OLP Financial Services Pakistan Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "OLPM",
    name: "OLP Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "OML",
    name: "Olympia Mills Limited",
    sectorName: "MISCELLANEOUS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ORM",
    name: "Orient Rental Mod",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "OTSU",
    name: "Otsuka Pakistan Limited",
    sectorName: "PHARMACEUTICALS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PABC",
    name: "Pakistan Aluminium Beverage Cans Limited",
    sectorName: "MISCELLANEOUS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PACE",
    name: "Pace (Pakistan) Limited",
    sectorName: "PROPERTY",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PAEL",
    name: "Pak Elektron Limited",
    sectorName: "CABLE & ELECTRICAL GOODS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PAKD",
    name: "Pak Datacom Limited",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PAKL",
    name: "Pak Leather Crafts Limited",
    sectorName: "LEATHER & TANNERIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PAKOXY",
    name: "Pakistan Oxygen Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PAKQATAR",
    name: "Pak Qatar Family Takaful Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PAKRI",
    name: "Pakistan Reinsurance Company Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PAKT",
    name: "Pakistan Tobacco Company Limited",
    sectorName: "TOBACCO",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PCAL",
    name: "Pakistan Cables Limited",
    sectorName: "CABLE & ELECTRICAL GOODS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PELPS",
    name: "Pak Elektron (Pref)",
    sectorName: "CABLE & ELECTRICAL GOODS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PGCL",
    name: "Pakistan Gum & Chemicals Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PGLC",
    name: "Pak-Gulf Leasing Company Limited",
    sectorName: "LEASING COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PIAHCLA",
    name: "PIA Holding Company Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PIAHCLB",
    name: "PIA Holding Company LimitedB",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PIBTL",
    name: "Pakistan International Bulk Terminal",
    sectorName: "TRANSPORT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PICT",
    name: "Pakistan International Container",
    sectorName: "TRANSPORT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PIM",
    name: "Popular Islamic Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PINL",
    name: "Premier Insurance Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PIOC",
    name: "Pioneer Cement Limited",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PKGI",
    name: "The Pakistan General Insurance Co. Ltd.",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PKGP",
    name: "Pakgen Power Limited",
    sectorName: "POWER GENERATION & DISTRIBUTION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PKGS",
    name: "Packages Limited",
    sectorName: "PAPER, BOARD & PACKAGING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PMI",
    name: "First Prudential Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PMPK",
    name: "Philip Morris (Pakistan) Limited",
    sectorName: "TOBACCO",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PMRS",
    name: "The Premier Sugar Mills",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PNSC",
    name: "Pakistan National Shipping Corporation",
    sectorName: "TRANSPORT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "POL",
    name: "Pakistan Oilfields Limited",
    sectorName: "OIL & GAS EXPLORATION COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "POML",
    name: "Punjab Oil Mills Limited",
    sectorName: "VANASPATI & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "POWER",
    name: "Power Cement Limited",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "POWERPS",
    name: "Power Cement (Pref)",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PPL",
    name: "Pakistan Petroleum Limited",
    sectorName: "OIL & GAS EXPLORATION COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PPP",
    name: "Pakistan Paper Products Limited",
    sectorName: "PAPER, BOARD & PACKAGING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PQGTL",
    name: "Pak Qatar General Takaful Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PREMA",
    name: "At-Tahur Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PRET",
    name: "Premium Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PRL",
    name: "Pakistan Refinery Limited",
    sectorName: "REFINERY",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PRWM",
    name: "Prosperity Weaving Mills Limited",
    sectorName: "TEXTILE WEAVING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PSEL",
    name: "Pakistan Services Limited",
    sectorName: "MISCELLANEOUS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PSO",
    name: "Pakistan State Oil Company Limited",
    sectorName: "OIL & GAS MARKETING COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PSX",
    name: "Pakistan Stock Exchange Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PSYL",
    name: "Pakistan Synthetics Limited",
    sectorName: "SYNTHETIC & RAYON",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PTC",
    name: "Pakistan Telecommunication Company Ltd",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "PTL",
    name: "Panther Tyres Ltd.",
    sectorName: "AUTOMOBILE PARTS & ACCESSORIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "QUICE",
    name: "Quice Food Industries Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "RCML",
    name: "Reliance Cotton Spinning Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "REDCO",
    name: "Redco Textiles Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "REWM",
    name: "Reliance Weaving Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "RICL",
    name: "Reliance Insurance Company Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "RMPL",
    name: "Rafhan Maize Products Company Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "RPL",
    name: "Roshan Packages Limited",
    sectorName: "PAPER, BOARD & PACKAGING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "RUPL",
    name: "Rupali Polyester Limited",
    sectorName: "SYNTHETIC & RAYON",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SAIF",
    name: "Saif Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SANSM",
    name: "Sanghar Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SAPT",
    name: "Sapphire Textile Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SARC",
    name: "Sardar Chemical Industries Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SASML",
    name: "Sindh Abadgars Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SAZEW",
    name: "Sazgar Engineering Works Limited",
    sectorName: "AUTOMOBILE ASSEMBLER",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SBL",
    name: "Samba Bank Limited",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SCBPL",
    name: "Standard Chartered Bank (Pak) Ltd",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SCL",
    name: "Shield Corporation Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SEARL",
    name: "The Searle Company Limited",
    sectorName: "PHARMACEUTICALS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SEL",
    name: "Sitara Energy Limited",
    sectorName: "POWER GENERATION & DISTRIBUTION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SEPL",
    name: "Security Papers Limited",
    sectorName: "PAPER, BOARD & PACKAGING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SERT",
    name: "Service Industries Textiles Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SFL",
    name: "Sapphire Fibres Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SGF",
    name: "Service GlobalFootwear Limited",
    sectorName: "LEATHER & TANNERIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SGPL",
    name: "S.G. Power Limited",
    sectorName: "POWER GENERATION & DISTRIBUTION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SHCM",
    name: "Shadman Cotton Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SHDT",
    name: "Shadab Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SHEL",
    name: "Shell Pakistan Limited",
    sectorName: "OIL & GAS MARKETING COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SHEZ",
    name: "Shezan International Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SHFA",
    name: "Shifa International Hospitals Limited",
    sectorName: "MISCELLANEOUS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SHJS",
    name: "Shahtaj Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SHNI",
    name: "Shaheen Insurance Company Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SHSML",
    name: "Shahmurad Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SIBL",
    name: "Security Investment Bank Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SIEM",
    name: "Siemens (Pakistan) Engineering",
    sectorName: "CABLE & ELECTRICAL GOODS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SILK",
    name: "Silkbank Limited",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SINDM",
    name: "Sindh Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SITC",
    name: "Sitara Chemical Industries Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SLCPA",
    name: "Security Leasing Corp.9.10%(Pref)",
    sectorName: "LEASING COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SLGL",
    name: "Secure Logistics Group Limited",
    sectorName: "TRANSPORT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SMCPL",
    name: "Safe Mix Concrete Limited",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SNAI",
    name: "Sana Industries Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SNBL",
    name: "Soneri Bank Limited",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SNGP",
    name: "Sui Northern Gas Pipelines Limited",
    sectorName: "OIL & GAS MARKETING COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SPEL",
    name: "SPEL Limited",
    sectorName: "PAPER, BOARD & PACKAGING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SPL",
    name: "Sitara Peroxide Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SPLC",
    name: "Saudi Pak Leasing Company Limited",
    sectorName: "LEASING COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SPSL",
    name: "Sitara Petroleum Service Limited",
    sectorName: "OIL & GAS MARKETING COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SPWL",
    name: "Saif Power Limited",
    sectorName: "POWER GENERATION & DISTRIBUTION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SRR",
    name: "Signature Residency Reit",
    sectorName: "REAL ESTATE INVESTMENT TRUST",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SRVI",
    name: "Service Industries Limited",
    sectorName: "LEATHER & TANNERIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SSGC",
    name: "Sui Southern Gas Company Limited",
    sectorName: "OIL & GAS MARKETING COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SSOM",
    name: "S.S.Oil Mills Limited",
    sectorName: "VANASPATI & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "STCL",
    name: "Shabbir Tiles & Ceramics Limited",
    sectorName: "GLASS & CERAMICS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "STJT",
    name: "Shahtaj Textile Limited",
    sectorName: "TEXTILE WEAVING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "STL",
    name: "Supernet Technologies Limited",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "STML",
    name: "Shams Textile Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "STPL",
    name: "Siddiqsons Tin Plate Limited",
    sectorName: "MISCELLANEOUS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "STYLERS",
    name: "Stylers International Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SURC",
    name: "Suraj Cotton Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SUTM",
    name: "Sunrays Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SWL",
    name: "Standard Worldwide Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SYM",
    name: "Symmetry Group Limited",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SYS",
    name: "Systems Limited",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "SZTM",
    name: "Shahzad Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TATM",
    name: "Tata Textile Mills Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TBL",
    name: "Treet Battery Limited.",
    sectorName: "AUTOMOBILE PARTS & ACCESSORIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TCORP",
    name: "Tariq Corporation Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TCORPCPS",
    name: "Tariq Corporation Limited(Pref)",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TELE",
    name: "Telecard Limited",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TGL",
    name: "Tariq Glass Industries Limited",
    sectorName: "GLASS & CERAMICS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "THALL",
    name: "Thal Limited",
    sectorName: "AUTOMOBILE PARTS & ACCESSORIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "THCCL",
    name: "Thatta Cement Company Limited",
    sectorName: "CEMENT",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TICL",
    name: "The Thal Industries Corporation Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TOMCL",
    name: "The Organic Meat Company Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TOWL",
    name: "Towellers Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TPL",
    name: "TPL Corp Limited",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TPLI",
    name: "TPL Insurance Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TPLL",
    name: "TPL Life Insurance Limited",
    sectorName: "TEXTILE SPINNING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TPLP",
    name: "TPL Properties Limited",
    sectorName: "PROPERTY",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TPLRF1",
    name: "TPL REIT Fund I",
    sectorName: "REAL ESTATE INVESTMENT TRUST",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TPLT",
    name: "TPL Trakker Limited",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TREET",
    name: "Treet Corporation Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TRG",
    name: "TRG Pakistan Limited",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TRIPF",
    name: "Tri-Pack Films Limited",
    sectorName: "MISCELLANEOUS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TRSM",
    name: "Trust Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TSBL",
    name: "Trust Securities & Brokerage Limited",
    sectorName: "INV. BANKS / INV. COS. / SECURITIES COS.",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TSMF",
    name: "Tri-Star Mutual Fund Limited",
    sectorName: "CLOSE - END MUTUAL FUND",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TSML",
    name: "Tandlianwala Sugar Mills Limited",
    sectorName: "SUGAR & ALLIED INDUSTRIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "TSPL",
    name: "Tri-Star Power Limited",
    sectorName: "POWER GENERATION & DISTRIBUTION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "UBDL",
    name: "United Brands Limited",
    sectorName: "MISCELLANEOUS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "UBL",
    name: "United Bank Limited",
    sectorName: "COMMERCIAL BANKS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "UBLPETF",
    name: "UBLPakistan Enterprise ETF",
    sectorName: "EXCHANGE TRADED FUNDS",
    isETF: true,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "UCAPM",
    name: "Unicap Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "UDLI",
    name: "UDL International Limited",
    sectorName: "MISCELLANEOUS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "UDPL",
    name: "United Distributors Pakistan Limited",
    sectorName: "MISCELLANEOUS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "UNIC",
    name: "The United Insurance Company",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "UNITY",
    name: "Unity Foods Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "UPFL",
    name: "Unilever Pakistan Foods Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "UVIC",
    name: "The Universal Insurance Company Limited",
    sectorName: "INSURANCE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "WAFI",
    name: "Wafi Energy Pakistan Limited",
    sectorName: "OIL & GAS MARKETING COMPANIES",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    "symbol": "WAHDAT",
    "name": "Wahdat Poultry Farm Limited",
    "sectorName": "FOOD & PERSONAL CARE PRODUCTS",
    "isETF": false,
    "isDebt": false,
    "isGEM": false
  },
  {
    symbol: "WAHN",
    name: "Wah Noble Chemicals Limited",
    sectorName: "CHEMICAL",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "WASL",
    name: "Wasl Mobility Modaraba",
    sectorName: "MODARABAS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "WAVES",
    name: "Waves Corporation Limited",
    sectorName: "CABLE & ELECTRICAL GOODS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "WAVESAPP",
    name: "Waves Home Appliances Limited",
    sectorName: "CABLE & ELECTRICAL GOODS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "WTL",
    name: "Worldcall Telecom Limited",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "YOUW",
    name: "Yousaf Weaving Mills Limited",
    sectorName: "TEXTILE WEAVING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ZAHID",
    name: "Zahidjee Textile Mills Limited",
    sectorName: "TEXTILE COMPOSITE",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ZAL",
    name: "Zarea Limited",
    sectorName: "TECHNOLOGY & COMMUNICATION",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ZIL",
    name: "ZIL Limited",
    sectorName: "FOOD & PERSONAL CARE PRODUCTS",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
  {
    symbol: "ZTL",
    name: "Zephyr Textiles Limited",
    sectorName: "TEXTILE WEAVING",
    isETF: false,
    isDebt: false,
    isGEM: false,
  },
];
